### ISSUE TITLE
Option to suppress discount message

### ISSUE THREAD

**Issue by bkonia** [habibillah/woocommerce-fixed-quantity#1]
For each product in the cart and on the checkout page, the plugin displays a message like:

(Incl. 10% discount)

Could you add an option in the settings to suppress this message, or perhaps add a box where the user can enter his own template for the message, or leave it blank to not display anything.

**Comment by habibillah** [comment]
Checkout 1.0.9 version. See http://sc.kalicode.net/sc_c0b4.png
