### ISSUE TITLE
all role option

### ISSUE THREAD

**Issue by lalop** [habibillah/woocommerce-fixed-quantity#3]
Is that possible to make this functionnality avalaible for all roles ?

**Comment by habibillah** [comment]
Go to `WooCommerce Settings >> Products >> Fixed Quantity`

**Comment by lalop** [comment]
I get this 
<img width="898" alt="capture d ecran 2016-07-13 a 14 57 15" src="https://cloud.githubusercontent.com/assets/313117/16804060/2339fa54-490a-11e6-9ee3-21dba9ae11f8.png">

But if I go on the page logged as admin I don't see the fixed quantity price feature.
Do you see what I mean ?

**Comment by habibillah** [comment]
See `default Role` and `Available Roles` fields.

**Comment by lalop** [comment]
Ok so I think there is an issue in the code
https://github.com/habibillah/woocommerce-fixed-quantity/blob/master/classes/woofix-utility.php#L84

When I come here the key is `customer` and current_user_roles is `[administrator]` so the function never show me the default price per quantity

**Comment by lalop** [comment]
sorry it's my fault, du to some change I did to support variation
